version: "3"

services:
    backend:
        build: ./
        volumes:
          - ./backend:/var/app
        links: 
          - client
          - database
        container_name: weatherapp_backend
        ports:
          - '5000:5000'

    client:
        image: mhart/alpine-node:8.11.3
        working_dir: /var/app
        volumes:
          - ./client:/var/app
        container_name: weatherapp_client
        ports:
          - '3000:3000'
        command: sh -c "yarn && yarn start"

    database:
        image: mongo:latest
        restart: always
        environment:
          - MONGODB_USER="root" 
          - MONGODB_PASS="topsecret"
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
          - '27017:27017'
        container_name: weatherapp_db